name: Keep App Awake

on:
  schedule:
    - cron: "0 */10 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Ping Real e Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          date +%s > .keepalive
          git add .keepalive
          git commit -m "chore: ping automatico para evitar hibernacao"
          git push
